### PR TITLE
TCM-111 | Build dummy calendar screen

### PR DESCRIPTION
**Pull request by halilyesilyurt**
### Summary

- [x] Completed dummy calendar screen.
- [x] Added calendar to test utility.

### Issue

[TCM-111](https://hyfnla.atlassian.net/browse/TCM-111)

### Video/Screenshot

| Calendar Has Event| Calendar No Event|
|--------|--------|
|calendar|calendar_no_event|

### CODE REVIEW

**Review by onodude — CHANGES_REQUESTED** [review]
looks good in general, lets resolve the conflicts please

**Comment by halilyesilyurt** [comment]
changed image.

**Comment by VivekV95** [comment]
Putting a hold on this as there are some improvements to the calendar module in PR for xpo and xpass

**Comment by VivekV95** [comment]
@halilyesilyurt Improvements are finished, they can be found here: https://github.com/hyfn/xpass-android/pull/269/files

**Comment by halilyesilyurt** [comment]
> @halilyesilyurt Improvements are finished, they can be found here: https://github.com/hyfn/xpass-android/pull/269/files

All improvements are completed for TRX.

**Comment by halilyesilyurt** [comment]
pr images updated.

**Review by VivekV95 — APPROVED** [review]

**Comment by VivekV95** [comment]
@halilyesilyurt I think this is good to go, just have to fix the merge conflicts

**Comment by onodude** [comment]
lets resolve the conflicts

**Comment by halilyesilyurt** [comment]
Resolved conflicts.

**Comment by VivekV95** [comment]
One more small change has been made on the Xpass side that we can implement here: https://github.com/hyfn/xpass-android/pull/304. Also, looks like some of the day initials are not appearing in my testing and in the demo: 
Screen Shot 2021-05-15 at 5 04 33 PM

**Comment by halilyesilyurt** [comment]
> One more small change has been made on the Xpass side that we can implement here: [hyfn/xpass-android#304](https://github.com/hyfn/xpass-android/pull/304). Also, looks like some of the day initials are not appearing in my testing and in the demo:
> Screen Shot 2021-05-15 at 5 04 33 PM

it was a small bug and i fixed.

**Comment by halilyesilyurt** [comment]
updated pr images.

**Review by VivekV95 — DISMISSED** [review]

**Review by onodude — APPROVED** [review]
thank you!

**Review by onodude — DISMISSED** [review]

**Review by onodude — APPROVED** [review]

**Pull request merged**
